version: '3'

services:
  missioncontrol:
    build: .
    command: 'nodemon server/start-servers.js'
    ports:
      - '8888:8443'
      - '9090:9090'
    environment:
      NODE_ENV: development
      DAV_ENV: simulated
      WEB_SERVER_PORT: 8443
      CAPTAIN_HOST: cap
      CAPTAIN_PORT: 4800
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - redis:redis
    external_links:
      - captain_captain-server_1:cap
    networks:
      - dav
  redis:
    image: redis
    networks:
      - dav

networks:
  dav:
    external: true
