version: '3'

services:
  missioncontrol:
    build: .
    ports:
      - '8888:8443'
      - '9090:9090'
    environment:
      NODE_ENV: development
      DAV_ENV: simulated
      WEB_SERVER_PORT: 8443
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    links:
      - redis:redis
  redis:
    image: redis
